version: '3.1'
services:
  neo4j:
    image: neo4j:4.0.0
    restart: always
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
      - ./neo4j/import:/import
    # could be expose: instead of ports for local docker network only
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    env_file:
      - .neo4j.env
    environment:
      # - NEO4J_AUTH=none # override .env
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
  mongo:
    image: mongo
    restart: always
    volumes: # does not work on windows
      - ./mongodb/data/db:/data/db
    # could be expose: instead of ports for local docker network only
    ports:
      - "27017:27017"
  api:
    build:
      context: ./api/
    volumes:
      - ./api:/app
    ports:
      - "80:5000"
    depends_on:
      - mongo
      - neo4j
    environment: # override .env
      - FLASK_DEBUG=0

